#!/usr/bin/env bash

# Shell prompt based on the Solarized Dark theme.
# Screenshot: http://i.imgur.com/EkEtphC.png
# Heavily inspired by @necolas’s prompt: https://github.com/necolas/dotfiles
# iTerm → Profiles → Text → use 13pt Monaco with 1.1 vertical spacing.

if [[ $COLORTERM = gnome-* && $TERM = xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
    export TERM='gnome-256color';
elif infocmp xterm-256color >/dev/null 2>&1; then
    export TERM='xterm-256color';
fi;

B='\[\e[1;38;5;33m\]'
LB='\[\e[1;38;5;81m\]'
GY='\[\e[1;38;5;242m\]'
G='\[\e[1;38;5;82m\]'
P='\[\e[1;38;5;161m\]'
PP='\[\e[1;38;5;93m\]'
R='\[\e[1;38;5;196m\]'
Y='\[\e[1;38;5;214m\]'
W='\[\e[0m\]'
BP='\[\e[1;38;5;117m\]'

cmd_status="\`if [ \$? = 0 ]; then echo -e '$G\xE2\x9C\x94$W'; else echo -e '$R\xE2\x9C\x98$W'; fi;\`"
prompt_symbol="\`[[ \$UID == 0 ]] && echo '#' || echo '$'\`"

prefix="$BP[\D{%m/%d %T}] $Y\u$GY@$P\h$GY:$B\W"
suffix="\n$cmd_status $prompt_symbol$W "

GIT_PROMPT_PATH="/usr/share/git/git-prompt.sh"
if [ -n "$1" ]; then
    GIT_PROMPT_PATH="$1"
fi;

if [[ $PS1 && -f $GIT_PROMPT_PATH ]]; then
    source $GIT_PROMPT_PATH

    export GIT_PS1_SHOWDIRTYSTATE=1
    export GIT_PS1_SHOWSTASHSTATE=1
    export GIT_PS1_SHOWUNTRACKEDFILES=true

    export PS1="$prefix\$(__git_ps1 \"$GY|$LB%s\")$suffix"
else
    export PS1="$prefix$suffix"
fi

export PS2="\[${Y}\]→ \[${W}\]";
